// Cohort service — real positional percentile distributions.
//
// Replaces the fabricated `syntheticPeers()` distributions the evaluation engine
// used to rank against. Each cohort is a SORTED array of real values recorded by
// qualifying players at that position last season, so a percentile means
// "better than N% of actual starters" rather than "better than N% of a bell
// curve we invented".
//
// Generated by scripts/preprocess-nflverse.mjs.
// Shape: { [position]: { [metric]: number[] } }  — ascending.

const DATA_URL = '/data/cohorts.json'

let _cohorts = null
let _meta = null
let _loadPromise = null

export async function loadCohorts() {
  if (_cohorts !== null) return _cohorts
  if (_loadPromise) return _loadPromise

  _loadPromise = fetch(DATA_URL)
    .then((r) => {
      if (!r.ok) {
        throw new Error(`Cohort data not found (${r.status}). Run: npm run preprocess-nflverse`)
      }
      return r.json()
    })
    .then((file) => {
      _cohorts = file.cohorts ?? {}
      _meta = file._meta ?? null
      _loadPromise = null
      return _cohorts
    })
    .catch((err) => {
      _loadPromise = null
      throw err
    })

  return _loadPromise
}

/** Sorted peer values for one position/metric, or null when not covered. */
export function getCohort(cohorts, position, metric) {
  const arr = cohorts?.[position]?.[metric]
  return Array.isArray(arr) && arr.length > 0 ? arr : null
}

/** Which season the cohorts were built from. */
export function getCohortMeta() {
  return _meta
}

// Test seam — lets the engine be exercised without a fetch.
export function __setCohorts(c, meta = null) {
  _cohorts = c
  _meta = meta
}
