// Market service — draft consensus (ECR/ADP) and the ID crosswalk that reaches it.
//
// Sleeper is the app's primary key space, but it publishes neither draft value
// nor bye weeks. Both come from FantasyPros consensus rankings, reached via a
// Sleeper -> FantasyPros id crosswalk. Generated by scripts/preprocess-nflverse.mjs.
//
//   player-ids.json  { players: { [sleeper_id]: { gsisId, fantasyprosId, ... } } }
//   adp.json         { players: { [fantasypros_id]: { ecr, sd, bye, ... } } }

const IDS_URL = '/data/player-ids.json'
const ADP_URL = '/data/adp.json'

let _cache = null
let _loadPromise = null

async function fetchJson(url, label) {
  const res = await fetch(url)
  if (!res.ok) {
    throw new Error(`${label} not found (${res.status}). Run: npm run preprocess-nflverse`)
  }
  return res.json()
}

/**
 * Resolves to { idsBySleeper, adpByFpId, meta }.
 * Memoised — many callers, one fetch pair.
 */
export async function loadMarketData() {
  if (_cache) return _cache
  if (_loadPromise) return _loadPromise

  _loadPromise = Promise.all([
    fetchJson(IDS_URL, 'Player id crosswalk'),
    fetchJson(ADP_URL, 'ADP data'),
  ])
    .then(([ids, adp]) => {
      _cache = {
        idsBySleeper: ids.players ?? {},
        adpByFpId: adp.players ?? {},
        meta: { ids: ids._meta ?? null, adp: adp._meta ?? null },
      }
      _loadPromise = null
      return _cache
    })
    .catch((err) => {
      _loadPromise = null
      throw err
    })

  return _loadPromise
}

// FantasyPros uses 3-letter codes for several teams where Sleeper uses 2-3.
// Needed for team defenses, which Sleeper keys by team abbreviation rather than
// a numeric player id, so the id crosswalk cannot reach them at all.
const TEAM_ALIASES = {
  GBP: 'GB', JAC: 'JAX', KCC: 'KC', LVR: 'LV',
  NEP: 'NE', NOS: 'NO', SFO: 'SF', TBB: 'TB',
  LA: 'LAR', WSH: 'WAS', ARZ: 'ARI', BLT: 'BAL', CLV: 'CLE', HST: 'HOU',
}

/** Normalise a team abbreviation to Sleeper's convention. */
export function normalizeTeam(code) {
  if (!code) return null
  const up = String(code).toUpperCase()
  return TEAM_ALIASES[up] ?? up
}

/** Build { sleeperTeamCode -> adp entry } for team defenses. */
export function buildDstTeamIndex(adpByFpId) {
  const index = {}
  for (const entry of Object.values(adpByFpId)) {
    if (entry.pos !== 'DST') continue
    const team = normalizeTeam(entry.team)
    if (team) index[team] = entry
  }
  return index
}

/** Normalised name key for the fallback match when no crosswalk entry exists. */
export function nameKey(name) {
  return (name ?? '')
    .toLowerCase()
    .replace(/\s+(jr|sr|ii|iii|iv|v)\.?$/, '')
    .replace(/[^a-z]/g, '')
}

/** Build { nameKey|position -> adp entry } so unmatched players get a second chance. */
export function buildAdpNameIndex(adpByFpId) {
  const index = {}
  for (const entry of Object.values(adpByFpId)) {
    if (!entry.name) continue
    const k = `${nameKey(entry.name)}|${entry.pos ?? ''}`
    // Overall-board entries win ties — they carry the more meaningful rank.
    if (!index[k] || entry.overall) index[k] = entry
  }
  return index
}

/**
 * Look up consensus data for one Sleeper player.
 * Returns { adp, adpSd, adpBest, adpWorst, bye, matchedBy } — matchedBy is
 * 'id' | 'name' | null so the UI can distinguish "no data" from "guessed".
 */
export function lookupMarket(player, { idsBySleeper, adpByFpId, adpNameIndex, dstTeamIndex }) {
  const empty = { adp: null, adpSd: null, adpBest: null, adpWorst: null, bye: null, matchedBy: null }

  // Team defenses never appear in the player-id crosswalk — Sleeper's id for
  // them IS the team code, so match on that directly.
  if (player.position === 'DEF') {
    const entry = dstTeamIndex?.[normalizeTeam(player.team) ?? normalizeTeam(player.id)]
    if (!entry) return empty
    return {
      adp: entry.ecr ?? null, adpSd: entry.sd ?? null,
      adpBest: entry.best ?? null, adpWorst: entry.worst ?? null,
      bye: entry.bye ?? null, matchedBy: 'team',
    }
  }

  const fpId = idsBySleeper?.[player.id]?.fantasyprosId
  let entry = fpId ? adpByFpId[fpId] : null
  let matchedBy = entry ? 'id' : null

  if (!entry && adpNameIndex) {
    entry = adpNameIndex[`${nameKey(player.name)}|${player.position}`]
    if (entry) matchedBy = 'name'
  }

  if (!entry) return empty

  return {
    adp: entry.ecr ?? null,
    adpSd: entry.sd ?? null,
    adpBest: entry.best ?? null,
    adpWorst: entry.worst ?? null,
    bye: entry.bye ?? null,
    matchedBy,
  }
}

/** gsis_id for a Sleeper player, for joining nflverse stats. */
export function gsisIdFor(sleeperId, idsBySleeper) {
  return idsBySleeper?.[sleeperId]?.gsisId ?? null
}
